### ISSUE TITLE
회원가입/로그인-API 연결-회원가입 API

### ISSUE THREAD

**Issue by gmlstjq123** [AirconMoa/AirconMoa-Android#17]
### 📌 내용
로그인 및 회원가입을 처리하기 위한 API를 연동한다.

### 🛠 ToDo
- [x] API를 사용하기 전에 서버를 연결한다. 
- [x] BaseResponse와 BaseUrl을 설정한다.
- [x] 카카오 소셜로그인 API 동작을 확인한다.(아직 MVP 적용 X)
