### ISSUE TITLE
CreateUserActivity-소셜로그인 및 파이어베이스-관련 설정

### ISSUE THREAD

**Issue by gmlstjq123** [AirconMoa/AirconMoa-Android#6]
### 📌 내용
회원가입 과정에서 필요한 UI와 관련 로직을 정의하고, 카카오 소셜로그인과 네이버 소셜로그인에 필요한 설정을 추가한다. 또한, 회원가입된 유저를 파이어베이스에 등록하기 위해 파이어베이스 관련 설정도 추가한다.

### 🛠 ToDo
- [x] 자동 로그인 기능 구현하기
- [x] 소셜 로그인 기능 구현하기
- [x] 파이어베이스 연동하기  
- [x] 액티비티 전환 애니메이션 추가하기
